### ISSUE TITLE
When used with MySql on AWS, Some SQL commands failed to execute 

### ISSUE THREAD

**Issue by maheshkelkar** [lookout/deploydb#103]
This problem was observed while testing DeployDb on EC2 instance and MySQL database on RDS instance in AWS.

Incompatibility between SQL syntax of H2 and MySql caused this problem.

Notablly, it failed to execute following commands in V3 of the migration:

SQL commands that worked on H2:
```
ALTER TABLE artifacts ALTER COLUMN groupName VARCHAR(8192);
ALTER TABLE artifacts ALTER COLUMN name VARCHAR(8192);
 
 /* No need for this index anymore */
DROP INDEX version_index;
 
CREATE UNIQUE INDEX artifact_version_index ON artifacts(groupName, name, version);
```

SQL commands that worked on MySql:
```
ALTER TABLE artifacts MODIFY COLUMN groupName VARCHAR(8192) NOT NULL;
ALTER TABLE artifacts MODIFY COLUMN name VARCHAR(8192) NOT NULL;
 
 /* No need for this index anymore */
DROP INDEX version_index ON artifacts;
 
CREATE UNIQUE INDEX artifactveridx ON artifacts ( groupName(50), name(50), version(50) );
```

The errors were as follows:
For ALTER TABLE:
```
Error executing statement at line 6: ALTER TABLE artifacts ALTER COLUMN groupName VARCHAR(8192)
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR(8192)' at line 1
```

For DROP INDEX:
```
Error executing statement at line 10: DROP INDEX version_index
```

For CREATE UNIQUE INDEX:
```
Specified key was too long; max key length is 767 bytes
Error executing statement at line 12: CREATE UNIQUE INDEX artifact_version_index ON artifacts(groupName, name, version)
```

**Comment by maheshkelkar** [comment]
Giri & I investigated further in this sql-incompatibility between H2 and MySQL; we have 3 choices:
define separate sql db migration files (duplicate scripts, maintainability issues, etc)
Write a script or contribute to existing github project mysql2h2-converter (time consuming, requires running this script on sql before every use)
Use flyway Java migrations. Here I am making an assumption that Driver name (H2 or mysql) will be available and will help us use the DB appropriate command and generate the appropriate SQL command.

**Comment by rtyler** [comment]
> Use flyway Java migrations. Here I am making an assumption that Driver name (H2 or mysql) will be available and will help us use the DB appropriate command and generate the appropriate SQL command.

To me this seems like the most reasonable option to me, with the most upside longer term. From my cursory search writing flyway migrations in Groovy (using their flyway-java APIs) should definitely be feasible too.

**Comment by maheshkelkar** [comment]
I am taking a hack at it
