### ISSUE TITLE
Webhooks should have a `type` field to differentiate event types

### ISSUE THREAD

**Issue by orrc** [lookout/deploydb#106]
As per [discussion](https://gitter.im/lookout/deploydb?at=550770aa63b7fd687a6cf1ed).

It would be convenient for webhook consumers to have a `type` field in the webhook payload, so that they can determine what type of webhook is being sent, e.g. whether it's "deployment created" or "promotion completed" or whatever.

**Comment by rtyler** [comment]
@tommysullivan makes a good point in Gitter about using specific media types on the POST to represent the different kinds of data. I'm not opposed to that

**Comment by tommysullivan** [comment]
And I'm not opposed to a type field but media types are a nice solution thanks for reposting @rtyler

**Comment by tommysullivan** [comment]
U can always add annotations for media type too, let jaxrs route for u (if that's what u r using as a hook recipient)

**Comment by rtyler** [comment]
I'm assigning this to myself to further define what we should actually do here

**Comment by orrc** [comment]
@rtyler I think we need this now, unless there's an alternative way just now for consumers (e.g. Jenkins plugins) to determine what type of event is being sent by inspecting the webhook payload?

**Comment by rtyler** [comment]
@GiriDandu @maheshkelkar I propose the following for "typing" webhook payloads:

A `Contentn-Type` header on the payload request that would be: `application/vnd.deploydb.<type>.v1+json`, e.g.:

 * `application/vnd.deploydb.deploymentcreated.v1+json`
 * `application/vnd.deploydb.deploymentcompleted.v1+json`

Provided that is well documented, I do not think we need a `type` field in the JSON

**Comment by tommysullivan** [comment]
+1!

Thank You,
Tom Sullivan
