### ISSUE TITLE
Deploydb code cleanup

### ISSUE THREAD

**Issue by GiriDandu** [lookout/deploydb#108]
This issue we will keep it open to do code cleanup. We are expecting to keep this issue open post 0.2 and capture issues related to names, conventions and other inconsistencies

Keep names of model/resources consistent
 - Environment should have webhook object not webhooks

**Comment by maheshkelkar** [comment]
Also, we should look into these codenarc errors. Some reason it doesnt stop the compilation

:codenarcMain
Compilation failed for [SourceFile[/Users/mkelkar/deploydb-0217/src/main/groovy/deploydb/ModelLoader.groovy]].
Compilation failed for [SourceFile[/Users/mkelkar/deploydb-0217/src/main/groovy/deploydb/WorkFlow.groovy]].
Compilation failed for [SourceFile[/Users/mkelkar/deploydb-0217/src/main/groovy/deploydb/models/Deployment.groovy]].
Compilation failed for [SourceFile[/Users/mkelkar/deploydb-0217/src/main/groovy/deploydb/models/PromotionResult.groovy]].
Compilation failed for [SourceFile[/Users/mkelkar/deploydb-0217/src/main/groovy/deploydb/registry/ModelRegistry.groovy]].

**Comment by maheshkelkar** [comment]
* Reorganize the contents of steps_definitions (i.e. move deployment specific steps to deploymentSteps.groovy, etc)
* There are various ways to create a Service -> using sampleService function, loading model from inline string, loading model from file, loading model from string in cucumber definition body, etc. Collate as much as possible. There are some unnecessary variations in attributes, fix them.
