### ISSUE TITLE
API needed to search for Artifacts based on version/name criteria

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#118]
In order to drive the entrypoint in to the Developer View of the web UI, we'll need the ability to search for a specific artifact by version (e.g. `1.0.3+deadbeef`), name (e.g. `verspaetung`) or some substring of one of those.

I'd suggest a paginated Artifact API as a GET off `/api/artifacts` with the `query` query parameter..

**Comment by GiriDandu** [comment]
Which of the following is preferable.

GET /api/artifacts/by-vesion/1.2.3.4:verspaetung
GET /api/artifacts/by-vesion/1.2.:verspaetung
This is what we do for group:name

or this.

GET /api/artifacts/by-version/verspaetung?query=1.2.3.4
GET /api/artifacts/by-version/verspaetung?query=1.2

**Comment by rtyler** [comment]
@GiriDandu what I was originally suggesting was actually neither of those options, but rather a `query` parameter on `/api/artifacts`

I.e.

`GET /api/artifacts?query=0xdeadbeef`

**Comment by GiriDandu** [comment]
@rtyler 

How does deploydb differentiate between following queries:

GET /api/artifacats?query=1.2.3.4 and
GET /api/artifacts?query=verspaetung

Don't we need extra parameter to qualify these queries to indicate it its query by version or by name ?
