### ISSUE TITLE
Make deployments self sufficient by storing config information in the DB objects

### ISSUE THREAD

**Issue by maheshkelkar** [lookout/deploydb#126]
Once the deployment is created, it reads entire applicable configuration and thus making it impervious to any future changes to the configuration.

Common changes:
* We already absorb most of the config information in to DB models (i.e. flow, deployment & artifact)
* As a part of this issue, we will have to store webhooks & some minor imp information from other config models (i.e. Service, Environment, Pipeline, promotion, etc) into DB models (i.e. flow, deployment & artifact).
* To keep track of changes to config, we need to add version numbers. 
  * Option-1:
    * Internally or externally get 1 config-version representing any change 
    * Limited or no impact on REST APIs

  * Option-2:
    * A separate version for each config model change (i.e. service, webhook, pipeline, environemnt, promotion, etc)
    * Will have impact on all REST APIs

**Comment by maheshkelkar** [comment]
This will have direct impact on #44

**Comment by polynomial** [comment]
Per discussion with @maheshkelkar, should have a version per config, both as a field in the file and as a field on the objects returned.

**Comment by rtyler** [comment]
@maheshkelkar for option 1:

> Internally or externally get 1 config-version representing any change 

I don't understand what this means, can you expand more? Is this just storing a copy of each version of configs and then referring to that globally?

and for option 2:

> Will have impact on all REST APIs

I don't understand how this will have an impact on the REST APIs at all, can you elaborate/quantify the impact a bit more?

**Comment by maheshkelkar** [comment]
> I don't understand what this means, can you expand more? Is this just storing a 
> copy of each version of configs and then referring to that globally?
Top level config.yml has a "version" field and chef must bump it up for each change to underlying service, environemtn, etc

> I don't understand how this will have an impact on the REST APIs at all, 
> can you elaborate/quantify the impact a bit more?

*options-2 talks about adding a version field for each model (service, pipeline, promotion, environment, etc).
* E.g. Flow will have (artifact, serviceIdent, service version, pipelineIdent, pipelineIdent, deployments)
* E.g. Deployment will have (artifact, environemntIdent, environment version, webhooks)
- Hence, I need to update JSON representation of the REST APIs that return deployment, flow, environment, service, etc
