### ISSUE TITLE
Model what a "Service" looks like

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#13]
Related to #7

**Comment by maheshkelkar** [comment]
What is the expectation from Issue? Defining REST API to create, read, delete service?

**Comment by rtyler** [comment]
For Service I don't think Create Update, Delete are necessary. I think this ticket was already resolved by that pull request you made yesterday defining the YAML loading

**Comment by maheshkelkar** [comment]
How does Service gets created? I thought that we would allow admin to create services and provide location of yaml file as an argument. 

If thats not true, do you see yaml file provided via DeployDb config during launch?

**Comment by rtyler** [comment]
@maheshkelkar Exactly, Service and other configuration-driven models should be placed on the machines running DeployDB. We'll want to provide an operational switch to reload that configuration, but that's definitely not something that we'd do in a RESTful fashion.

Configuration files we're expecting to be installed by Chef

**Comment by maheshkelkar** [comment]
I assume that:
- Service, Environment, Promotions, and Pipeline are all configuration driver models.
- Configuration files for all of these models are installed by Chef (I dont know how, but we will get into that later)
- Operational switch to reload configuration - would that be RESTful?

**Comment by rtyler** [comment]
> Service, Environment, Promotions, and Pipeline are all configuration driver models

Correct

> Configuration files for all of these models are installed by Chef (I dont know how, but we will get into that later)

Correct, there's nothing to worry about there.

> Operational switch to reload configuration - would that be RESTful

Yes,. but outside the scope of 0.1.0 and probably 0.2.0 though

**Comment by maheshkelkar** [comment]
As per exchange above, this issue is taken care by #36
