### ISSUE TITLE
running documentation changes

### ISSUE THREAD

**Issue by polynomial** [lookout/deploydb#137]
for the running doc:
http://hackers.lookout.com/deploydb/running.html
from:
src/asciidoc/running.ad
We should probably have a 'hacking on or building' doc that has how you have to use gradlew to build it. The running it doc should point you at a cut release. The last thing i ever want to do with a new open source project is download it, and wait 5 minutes and get an error:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/bsmith/src/deploydb/build.gradle' line: 166

* What went wrong:
A problem occurred evaluating root project 'deploydb'.
> net.rubygrapefruit.platform.internal.jni.PosixFileFunctions.chmod(Ljava/lang/String;ILnet/rubygrapefruit/platform/internal/FunctionResult;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 24.067 secs

The 'running' it doc should point them towards using bintray and the examples need to be working, currently we *don't* ship an 'example.yml' so this command will never work:
  java -jar build/libs/deploydb-0.1.0.jar server example.yml

The commands in here should probably have version abstraction so they don't need to be updated per release (or the docs need to be generated with the release available on bintray).

**Comment by GiriDandu** [comment]
closed with #140 . The docs are updated accordingly
