### ISSUE TITLE
DeployDB should accept/store more detailed version information

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#16]
We had some discussions around this a long time ago inside of @Lookout, but the gist of the idea would be to allow tooling in Jenkins (for example) to publish the full dependency tree for a `.war` artifact.

This might just be the parse output of `./gradlew dependencies` for all I care, but being able to look up the disparate versions of dependencies between artifacts would be valuable both in aggregate ("who's using jruby-jars 1.7.16?") and in a debuggin scenario ("what went into this artifact?")

**Comment by csanders-lookout** [comment]
That sounds like a good idea. I assume you're including the transitive
dependencies. For me, the most human readable way to do that is with
dependency:tree

**Comment by rtyler** [comment]
@csanders-lookout yeah, my thinking does include transitive dependencies particularly for java-based artifacts.

**Comment by csanders-lookout** [comment]
Yeah - then we should push a similarly version dependency tree flat file
for each war. Or, alternatively, we could put it in the war metadata
directory. It'll be pretty small.

**Comment by csanders-lookout** [comment]
similarly version*ed*

On Wed, Jan 14, 2015 at 11:17 AM, Carter Sanders <carter.sanders@lookout.com

**Comment by rtyler** [comment]
I spoke with @cbleach about this IRL and for the purposes of baking AMIs and using DeployDB to track AMIs through a pipeline (as artifacts).  We would want to know all the version information not only of the artifact (e.g. `.war`) but also the versions of cookbooks, etc that were used to bake the AMI.

**Comment by csanders-lookout** [comment]
OK - so that's more than maven will give us. Sounds like we need a custom
script.

**Comment by rtyler** [comment]
After much discussion with @polynomial on the subject he's convinced me that this should not go into DeployDB. There's a definite requirement for it somewhere in the Ci/CD ecosystem so maybe we'll build an ArtifactDB at some point, but for now I'm closing this with prejudice :)

**Comment by GiriDandu** [comment]
Here are my thoughts on #16 and #20.

To answers the questions described in the issue. We need to model the dependency information as a "artifact dependency graph".   Libraries we should look at are. JUNG, JGraphT, neo4j. An approach to store the graph data in persistent memory can be what's described in this presentation. http://www.slideshare.net/billkarwin/models-for-hierarchical-data
