### ISSUE TITLE
UAT artifact incorrectly named.

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#181]
See [the 0.3.1 release in Bintray](https://bintray.com/lookout/systems/DeployDB/0.3.1/view#files)

Basically the group should be the same, `deploydb` instead of `uat` and the artifact's name should be `deploydb-uat`. The latter is easily accomplsihed by making the `uat/` dir named `deploydb-uat/`

**Comment by GiriDandu** [comment]
OK, I will make the change
