### ISSUE TITLE
Deployments are rendered twice

### ISSUE THREAD

**Issue by emilong** [lookout/deploydb#183]
This is the output of api/deployments:
https://gist.githubusercontent.com/emilong/fb43b7e5862ba159eb5c/raw/53e438c44456841bef797622e0a1c7a73187fe24/gistfile1.json
Notice that models with the same id appear twice.

Steps to repro:
- get this branch: https://github.com/emilong/deploydb/tree/multi-env-pipeline
- ./gradlew shadowJar
- java -jar build/libs/deploydb-*-all.jar db migrate complicated/deploydb.launch.yml
- java -jar build/libs/deploydb-*-all.jar server complicated/deploydb.launch.yml
- post this:
```shell
curl -X POST -H  "Content-Type: application/json" http://localhost:8080/api/artifacts -d "{
  \"group\" : \"immortan.joe\",
  \"name\": \"mask\",
  \"version\" : \"da39a3ee5e6b4b0d3255bfef95601890afd80709\",
  \"sourceUrl\" : \"http://example.com/immortan.jar\"
}"
```
- curl http://localhost:8080/api/deployments

**Comment by emilong** [comment]
FYI: This appears to be an issue in the way we're invoking Hibernate to get the deployments. Specifically, that model left outer joins some of its relations, so we can get multiple deployments on the left side when we have many of the have many relations on the right. Adding `.setResultTransformer(Criteria.DISTINCT_ROOT_ENTITY)` to the criteria() result in DeploymentDAO fixed it for me, though I don't have a test to validate.

**Comment by GiriDandu** [comment]
@emilong thanks for triage. 

Another approach to fix this is to make selection unique in the DB itself using projection instead of doing post DB with Transformer.  Using following 
Projections.distinct(Projections.property("id"))

We will consider both approaches and fix the bug.

**Comment by emilong** [comment]
@GiriDandu ah cool. In DB seems like a much better solution. TBH, I think this endpoint is going to have a lot of records very quickly, so it feels better to put the deduping in DB rather than sending it over the wire first.
