### ISSUE TITLE
Expose API for listing Deployments (i.e. Artifacts/Services) in a given Environment

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#21]
Given the name of an environment, I should be able to find out "what" is in that environment

Kinds of information that would be useful to list:

 * List of Artifacts with their version information
 * Artifact status (i.e. Promotion Criteria met)

**Comment by maheshkelkar** [comment]
@rtyler whats the requirement here:
GET on /api/environments/<environment-name>/artifacts 
returns LIST of "artifact (id, group, name, version, url, time) +  deployment-STATUS"

**Comment by maheshkelkar** [comment]
In fact I think we should change the description to say that "Expose API for listing deployments in a given Environment"

**Comment by maheshkelkar** [comment]
@rtyler whats the requirement here:
GET on /api/environments/environment-name/artifacts 
OR
GET on /api/deployments/by-environment/environment-name 

returns LIST of deployments (that contain all the required information)

**Comment by rtyler** [comment]
@maheshkelkar Sorry for the lack of clarify, this means:

`GET /api/environments/${name}/artifacts`

This would power an environment dashboard in the front-end where we would need to know this information, in as few as requests as possible in an ideal case

**Comment by maheshkelkar** [comment]
The response is expected to contain LIST of artifacts, service-ident & deployment-status (in essence entire deployment; hence I thought we can return the whole deployment)

**Comment by rtyler** [comment]
@maheshkelkar if you think it will be better/cleaner to just return the current deployments in each environment, then let's change this to `api/environments/${name}/deployments`?

**Comment by maheshkelkar** [comment]
Yes, I will change it and push again
