### ISSUE TITLE
sourceUrl should be required to create an Artifact

### ISSUE THREAD

**Issue by maheshkelkar** [lookout/deploydb#23]
Without a sourceUrl in the Artifact create request, the Artifact is really not a useful concept.

```cucumber
Scenario: The request should fail when creating an Artifact without a sourceUrl
    When I PUT to "/api/v1/artifacts" with:
    """
      {
        "group" : "com.example.cucumber",
        "name" : "cukes",
        "version" : "1.2.345"
      }
    """
    Then the response should be 400

```

**Comment by rtyler** [comment]
[This section on validation of representations](http://dropwizard.io/manual/core.html#validation) from the Dropwizard manual might be relevant to your interests
