### ISSUE TITLE
Administrators should be able to configure webhooks for deployment creation

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#35]
Related to #18 

I've been thinking of webhooks as something to be configured in yaml, [example here](http://hackers.lookout.com/deploydb/internals.html#_configuring_webhooks).

This doesn't prescribe the payload of those webhooks, which is something I think we still need have some discussion around.

@polynomial might have some thoughts on how we should handle this as well.

**Comment by maheshkelkar** [comment]
@rtyler now that we are loading webhooks via yaml config, is this issue valid anymore?

**Comment by maheshkelkar** [comment]
@GiriDandu @rtyler can we close this issue now?
