### ISSUE TITLE
We need some ability to deserialize YAML into Models

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#36]
We've got [some examples}(http://hackers.lookout.com/deploydb/internals.html#_services) where we need to define something that approximates a "model" in the DeployDB codebase.

Dropwizard itself has support for a single configuration file, but we need some ability to define YAML-backed models.

For example, `services/auditlog.yml` would eventually be translated into a `deploydb.models.Service` instance for auditlog.

I don't want this issue to include the handling of loading those yaml files necessarily, but the code to translate configuration-driven models from YAML into objects.

**Comment by maheshkelkar** [comment]
are we using dropwizard <http://dropwizard.io/getting-started.html#creating-a-configuration-class> to convert yaml to objects?

**Comment by rtyler** [comment]
@maheshkelkar that's what `DeployDBConfiguration` actually is. This has a number of problems for modeling things like services, etc.

Namely, this is the configuration for how the application should run, the number of threads, the logging, etc. It's not something that I've seen used for "configuration data" like we've got here with "services" (for example).

Secondly, it's *all one file*. I'd like us to be able to avoid trying to manage one gigantic file for everything YAML configuration-based. Separate files means that @polynomial has a lot of flexibility in how he delivers various Service and Pipeline definitions to DeployDB

**Comment by maheshkelkar** [comment]
@rtyler so if I understand correctly, we need to have our own set of yaml files; and methods for the DeployDbApplication to read them into objects (which I assumed will have to be pre-defined, per service).

**Comment by rtyler** [comment]
For this ticket I'm not worried about wiring this into `DeployDBApplication` just yet. I want to start with the Jackson code necessary to turn YAML into models, like `Service`

Once we get that to where we like it, we should wire it into the application separately

**Comment by maheshkelkar** [comment]
Is this what we are trying to do?

Added a foas.yml (will change to appropriate name & contents later) file:
src/main/resources/services/foas.yml

I have defined service objects in the models directory:
src/main/groovy/deploydb/models/ServiceModel.groovy

Test valid file:
src/test/resources/services/services-test-valid.yml

As a part of tests, I have wrote some jackson code to read yaml file and convert it into service objects. I assume we can use for the actual parsing as well:
src/test/groovy/deploydb/models/serviceSpec.groovy ->

```
class ServiceWithArgsSpec extends Specification {

    private final Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
    private final ConfigurationFactory<ServiceModel> factory =
            new ConfigurationFactory<>(ServiceModel.class, validator, Jackson.newObjectMapper(), "dw");
    
   def "loadsValidConfigFiles"() {
        given:
        ClassLoader classLoader = getClass().getClassLoader();
        File validFile = new File(classLoader.getResource("services/services-test-valid.yml").toURI());
        ServiceModel serviceModel = factory.build(validFile);

        expect:
        serviceModel.getName() == "Fun as a Service";
        serviceModel.getArtifacts().get(0) == "com.github.lookout:foas";
        serviceModel.getArtifacts().get(1) == "com.github.lookout.puppet:puppet-foas";
        serviceModel.getArtifacts().get(2) == "com.github.lookout:puppet-mysql";
        serviceModel.getPipelines().get(0) == "devtoprod"
        serviceModel.getPromotions().get(0) == "status-check"
        serviceModel.getPromotions().get(1) == "jenkins-smoke"
    }
```

**Comment by rtyler** [comment]
Yes, I think you're largely on the right track. You might want to spend some more time learning about how Groovy makes your life easier though! Trailing semi-colons aren't necessary, for example. Also:

`serviceModel.getArtifacts().get(0) == "com.github.lookout:foas";`

Can be turned into:

```groovy
serviceModel.artifacts[0] == 'com.github.lookout.foas'
```

Basically, methods on objects named "getFoo()" and "setFoo(F)" can be treated like properties, e.g. "x.foo" and "x.foo = f"


Once this code is worked out, we'll want to figure out how we should load the files, since `src/main/resources` is not where Lookout's own internal service file definitions will be stored. `/etc/deploydb/services/` more likely.

**Comment by maheshkelkar** [comment]
Hmmm, I spent quite some time understanding and fixing the part of locating the services/services-test-valid.yml file under src/test/resources. Because the ```new File(classLoader.getResource("services/services-test-valid.yml")```, could not find that file when placed under (say src/test/groovy/deploydb/resources/)

In general, how do I provide full path to Resources.getResources(...) function? Or if its a partial path, how do I get the current directory

**Comment by rtyler** [comment]
@maheshkelkar that kind of stuff I really didn't want to address in this issue for exactly this reason. `Resources` from my understanding is a special nomenclature in the JVM to find files coupled with resources in the classpath.

For these files, we're going to want to load them from a fixed path, which is just normal POSIXy file loading semantics.

**Comment by maheshkelkar** [comment]
For services yaml file, is it fair to say that:
name - can't be null, mandatory
artifacts - at least one must be present
piplines - at least one must be present
promotions - may or may not be present

**Comment by rtyler** [comment]
@maheshkelkar :+1:
