### ISSUE TITLE
Expose Services via a read API

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#43]
Since Services are configuration driven, I think all we need is an API to list all services (e.g. `/services`) and an API to list details about a specific service (e.g. `/services/<name>`)

**Comment by maheshkelkar** [comment]
@rtyler perhaps this will be part of our discussion today. But what is the purpose of this API? a) just for display purpose, OR b) you see deploydb's client accessing this information somehow (how?)

**Comment by maheshkelkar** [comment]
@rtyler once read from config, I assume we will have store them in DB as well. If not, are we going to hold them into some table in memory?

**Comment by rtyler** [comment]
@maheshkelkar The API would be much more for display purposes, in order for a developer to understand what artifacts compose a service, we would need to expose the service data to a CLI or frontend client.

As for storing this in the database, that's unnecessary, we'll just need to store these in a memory accessible fashion. My current thinking is creating a `ServiceRegistry` object, an instance of which can be created in the loading of `DeployDBApp`  passed into a `ServiceResource`. Similar to how we pass the DAO objects into resources.

**Comment by maheshkelkar** [comment]
@rtyler can you please point me to example similar to ServiceRegistry object mentioned above.

**Comment by rtyler** [comment]
@maheshkelkar The way that [dao objects are passed into Resource instantiation](https://github.com/lookout/deploydb/blob/master/src/main/groovy/deploydb/DeployDBApp.groovy#L96) is the model I'm suggesting. Now `ServiceRegistry` wouldn't be a dao object (i.e. not inheriting from `AbstractDAO`) but the use case looks similar in my view

**Comment by maheshkelkar** [comment]
@rtyler I assumed that we are talking about using an extant class for ServiceRegistry OR using hibernate without DB underneath. 

If we have to write SessionRegistry from ground up, I assume it needs a map to store all service instances and provide methods to walk them (key: name). 

For creating Service instances from YMAL files, we're using ConfigurationFactory<Service>. When creating Service objects in testcode, We can use empty build() method to create default object and populate it as required.

**Comment by rtyler** [comment]
@maheshkelkar I would honestly write a simple POJO (plain old java object) that encapsulates a `ConcurrentHashMap` for now and instantiate it in the `DeployDBApp` class.

Here's an abstract interface  proposal for the registry:

```groovy
abstract class AbstractModelRegistry<Class T>  {
  // I'm not convinced String is the right type to carry that configuration dir in
  abstract AbstractModelRegistry(String configDirectory)

  // I would assume this would serve initial and reload usecases
  abstract loadModels()

  abstract T getModelByName(String name)

  abstract List<T> getAllModels()
}
```

I'm not sure what else we would need other than that right now really
