### ISSUE TITLE
DeployDB should be able to reload configuration with an API call

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#44]
In order to support a CLI tool which might `deploydb reload` we should implement a simple REST call which will force DeployDB to reload *all* configuration files on disk.

Not sure where in the URL space this should live, but it might make sense to add it to the Admin app that Dropwizard runs side-by-side with the app itself

**Comment by maheshkelkar** [comment]
The reload should fail if deployDb is actively deploygin i.e. if there are any active flows/deployments

**Comment by maheshkelkar** [comment]
@rtyler if we have multiple instances of deployDB app running, do we expect admin app to upload config and reload config on all the instances?

**Comment by rtyler** [comment]
@maheshkelkar that's a good question. I'm curious what @polynomial and @mbbx6spp think on this issue.

**Comment by maheshkelkar** [comment]
@rtyler If we store configuration models in DB, then admin doesn't have to update all the instances. 

For uploading the config, another alternative is to have admin pass the URL of config file locations with reload API. The deployDB can turn around and attempt to read config files from that (http://<host>/services/<files>); However, I am not sure if we can GET file(s) or iterate thr files from a URL

**Comment by rtyler** [comment]
@maheshkelkar configuration in a DB is poor design choice (IMHO) and one that causes a lot of frustration for operating a service.

I think it might be perfectly fine to make configuration reloading host specific, and then when we get around to having a CLI or something like that, the configuration reloading support would require an explicit host option

**Comment by maheshkelkar** [comment]
@rtyler is this something that chef can do? That is uploading new config files and triggering configuration reload on all the instances?

**Comment by rtyler** [comment]
@maheshkelkar yep!

**Comment by maheshkelkar** [comment]
@rtyler I assume chef will copy the config to "configDirectory" location and use REST API to trigger the configuration reload. The REST API would not have any input (effectively an empty POST to the path). 

The deployDB will load the config from "configDirectory" specified in its configuration.

**Comment by rtyler** [comment]
@maheshkelkar assumption correct!
