### ISSUE TITLE
How DeployDb loads yaml-based/configuration-driven models

### ISSUE THREAD

**Issue by maheshkelkar** [lookout/deploydb#45]
The Service, Environment, Promotions, and Pipeline are all configuration-driven models. 

During launch, the DeployDb needs to read the YAML file for each of these models and create their instances.

**Comment by maheshkelkar** [comment]
@rtyler for location of all yaml files, do we assume a fixed path (e.g. /etc/deploydb/resource) OR read it from the DeployDb specific configuration file (i.e. deploydb.example.yml)

**Comment by rtyler** [comment]
@maheshkelkar the location of service files should be read from the "primary" configuration file in my opinion, @polynomial can correct me if he thinks otherwise

**Comment by maheshkelkar** [comment]
@rtyler @polynomial @GiriDandu 
To load configuration files during launch, I propose the following:

- New attribute in the primary configuration file
e.g. deploydb.example.yml OR deploydb.cucumber.yml

- The new attribute is as follows:
 "configFilesPath: "/etc/deploydb"

- During launch DeployDbApp will read Service, Environment, Promotion, Pipeline and webhooks from their own subdirectories to populate models:
E.g. 
- services/faas.yml (i.e. /etc/deploydb/services/faas.yml) - for services
- environments/integ.yml (i.e. /etc/deploydb/environment/integ.yml) - for environments
etc

**Comment by GiriDandu** [comment]
@maheshkelkar I like this idea in general. Instead of "configFilesPath" can we change this "configDirectory"

**Comment by polynomial** [comment]
Agree with @rtyler about the initial location read from the primary config. I'm hoping the rest can be:
* read with just a signal, not a restart
* on failure to validate, should not break the service
* do not need to be explicitly defined anywhere (it should recurse the configFilesPath directory and load everything ending in .yml)

**Comment by rtyler** [comment]
@maheshkelkar I also like `configDirrectory` as the key name in the primary configuration. Dropwizard already provides a command line flag for specifying where that primary configuration is so that should be enough.

To @polynomial's requests, items one and two we shouldn't address right now, but the configuration file handling code should be written such that we can call it multiple times thorughout the lifetime of the application (boot, and then multiple times later).

**Comment by maheshkelkar** [comment]
@rtyler, @GiriDandu configDirectory it is. I have experimented in defining this as an attribute in deploydb.yml; I assume dropwizard should automagically allow that into command line option. 

We need a <way> to determine whether "file.yml" is for service, environment, etc model; One of the way I suggested was to have files grouped in the subdirectory

yes, we can provide a function to load all files, at boot time or triggered by a REST API (button on the web page)

**Comment by polynomial** [comment]
It seems like the service vs blah should be in the yaml itself.
service: faas
  other: stuff
  more: other-things

**Comment by maheshkelkar** [comment]
@polynomial This would require partial parsing capability; first to parse the type and then to parse the entire model, because every model is different.

**Comment by rtyler** [comment]
@maheshkelkar directory-based distinction is fine for me, i.e.

* `/etc/deploydb/conf/environments/production.yml`
* `/etc/deploydb/conf/services/faas.yml`

**Comment by GiriDandu** [comment]
:+1:
