### ISSUE TITLE
Update Deployment Model to include Service, Promotion Status for the Artifact deployed

### ISSUE THREAD

**Issue by GiriDandu** [lookout/deploydb#48]
Deployment should serialize a "service" value as well as "environment"

**Comment by maheshkelkar** [comment]
I am proposing following Mapper classes for Deployment

/* In memory object */
Deployment {
    Artifact artifact //reference
    Environment environment // reference
    Service service // reference
    State state
    PromotionStatus { ident, State, infoUrl)
}

/* Reading & writing to Db */
DeploymentDbMapper {
    Artifact artifact //reference OneToOne with Artifact
    String environment
    String service
}
why do we need this?
- Artifact reference is looked by hibernate; But, for conversions between ServiceId & Service, EnvironmentId & Environment object, we need this mapper.


/* JSON response */
DeploymentResponseMapper {
    Artifact artifact //reference
    String environment
    String service
    State state
    PromotionStatus { ident, State, infoUrl)
}
Why do we need this?
We dont want to expose entire Service or Environment object, so we need this to pick and choose what to expose.

**Comment by GiriDandu** [comment]
Service, Environment and Promotion will be used in other objects in Webhooks, Flow etc. Can we make this generic. If its non trivial, then we can use separate mapper objects

**Comment by maheshkelkar** [comment]
I deleted my comment about mapping. For the timebeing lets store serviceIdent & envinronmentIdent as String inside the Deployment object; we will perform in memory lookups for all the operations. Later we will sync up on how do this with more magic :)
