### ISSUE TITLE
Use yaml filename as a key (id) for Service Model instance

### ISSUE THREAD

**Issue by maheshkelkar** [lookout/deploydb#53]
All the configuration driven models (i.e. service, environment, pipeline, webhooks, promotions, etc) are created from yaml file. Use the filename as the "id" in the object instance created from the config.

**Comment by rtyler** [comment]
In this change will you also change the property name in the configuration files from "name" to "description" per our IRL discussion yesterday?

**Comment by rtyler** [comment]
Isn't this fixed now? You can set up commit messages to auto-close issues by the way with `Fixes #53` at the bottom of the commit message

**Comment by maheshkelkar** [comment]
Yeah. I had a #53 in each commit. Not sure why it didnt close. But in git :)
