### ISSUE TITLE
Model what an "Environment" looks like

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#8]
Environment:

>  a collection of applications and configurations for executing services together across a cluster of machines.

----

Currently my thinking is that an environment is nothing more than a name of something really. Other tools like CloudFormation or a Terraform plan might contain the actual definition of what's "in" an environment. All `#DeployDB` should really care about right now is a "name" as far as I can tell

**Comment by rtyler** [comment]
Related to #17

**Comment by maheshkelkar** [comment]
I assume as a part of this ticket, we need to define Model and unit tests to verify yaml to instance conversion. If true, same thing can be said about #3 (promotion) and #9 (pipline), right?

**Comment by rtyler** [comment]
@maheshkelkar :+1:  yes indeed!

**Comment by maheshkelkar** [comment]
The fix is merged
