### ISSUE TITLE
Allow defining a Pipeline via YAML

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#9]
Pipeline:

> a set of deployments and promotions defining the relationships between each environment

Current thinking of `pipelines/cd-prod-pipeline1.yml`

```yaml
environments:
  - dev-alpha
  - dev-beta
  - integ
  - preprod
  - prod
```

I'm currently thinking about pipelines as a plural because one might have a couple different continuous delivery pipelines going on at once. For example, web services might be deployed with a simple dev -> prod pipeline, but less stable or more problematic services would go through different UAT environments before production.

### Open Questions

 * Should we be able to specify additional promotion criteria in the pipeline yaml file? E.g. promotion to the `prod` environment always requires a clean status check from `preprod` *and* a manual promotion?
 * Are environments defined anywhere else other than tacitly in the pipeline file?

**Comment by rtyler** [comment]
I've further defined this in [this document](http://hackers.lookout.com/deploydb/internals.html#_pipelines) which roughly approximates a specification

**Comment by maheshkelkar** [comment]
@GiriDandu can we close thie issue? I think its merged
