### ISSUE TITLE
Release 0.1.0 to Bintray

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#91]
Per @polynomial's request we'll publish a zipball to Bintray for consumption

**Comment by GiriDandu** [comment]
@rtyler should we do the same thing on AWS also?

**Comment by rtyler** [comment]
@GiriDandu  Nah, this is just a release process ticket for me to handle

**Comment by rtyler** [comment]
[Blammo](https://bintray.com/lookout/systems/DeployDB/0.1.0/view)
